# Generated by Django 4.2.7 on 2023-12-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField()),
                ('original_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=200)),
                ('thumb_frame', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=100)),
                ('video_path', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_app.videocontent')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_app.videotag')),
            ],
        ),
    ]
