# Generated by Django 4.2.7 on 2023-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField()),
                ('original_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=200)),
                ('is_url_link', models.BooleanField()),
                ('url', models.URLField(max_length=1000, null=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('tags', models.ManyToManyField(to='video_app.tag', verbose_name='タグ')),
            ],
        ),
    ]
