# Generated by Django 4.2.7 on 2023-12-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_app.video', verbose_name='動画')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_account', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
