# Generated by Django 4.2.7 on 2023-12-02 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotag',
            name='user',
        ),
        migrations.CreateModel(
            name='UserRefTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video_app.videotag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
