# Generated by Django 4.2.7 on 2023-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_remove_videotag_user_userreftag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='video_path',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='url_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
