# Generated by Django 4.2.7 on 2023-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='video_app.tag', verbose_name='タグ'),
        ),
    ]
